### ISSUE TITLE
question: how to make color variable fonts

### ISSUE THREAD

**Issue by aminabedi68** [adobe-type-tools/opentype-svg#19]
Hi
thank you for this great tool, it's amazing!
i'm an amateur font designer recently working on color fonts, i need to know how can i use opentype-svg along with fontmake to create a color variable font, fontmake input formats for variable font masters are UFO(with designspace file) and glyphs so i can't use otf(i tried to convert but didn't work).

**Comment by miguelsousa** [comment]
Thanks Amin.

The [`SVG` table](https://docs.microsoft.com/en-us/typography/opentype/spec/svg) does not support variations, so at this time it's not possible to make variable OpenType-SVG fonts.

You can, however, make variable color fonts if you use the format that leverages the `COLR` and `CPAL` tables. The tools in this repo won't help you with that.

I suggest you get in touch with Roel Nieskens (@RoelN). He's a font wizard and has been stress-testing color font technology for years.
