### ISSUE TITLE
fonts2svg viewBox is calculated incorrectly

### ISSUE THREAD

**Issue by davidgodzsak** [adobe-type-tools/opentype-svg#22]
I think to calculate the viewbox correctly we could use the minX, minY, maxX and maxY parameters from TTF header table instead of unitsPerEm. I have some fonts I transform with this tool that get clip out from the viewbox.

How could I submit a PR to fix this?

**Comment by miguelsousa** [comment]
Please share the examples that suggest that the current logic is incorrect.

**Comment by davidgodzsak** [comment]
Here are a few examples using KoHo-Regular from google fonts:

J:
<img width="194" alt="Screenshot 2021-05-22 at 21 34 47" src="https://user-images.githubusercontent.com/11213866/119238912-cd833e00-bb45-11eb-920f-a3efd4dddcd5.png">

,:
<img width="187" alt="Screenshot 2021-05-22 at 21 34 10" src="https://user-images.githubusercontent.com/11213866/119238919-dc69f080-bb45-11eb-90b1-09c676efdfd0.png">

}:
<img width="198" alt="Screenshot 2021-05-22 at 21 33 47" src="https://user-images.githubusercontent.com/11213866/119238922-e12ea480-bb45-11eb-83a2-f2c1c3440acc.png">

**Comment by miguelsousa** [comment]
The SVGs are being generated as expected. The parts of the glyphs that are not visible are below the font's baseline.
For your purposes, adjusting the viewBox may be something desired but it's a kind of change that should be done by default. If you want to submit a patch, put it behind an option.

**Comment by davidgodzsak** [comment]
Hmm makes sense, but wouldn't it be desirable to also render the descender and a line gap under the font, when creating the SVG?

**Comment by miguelsousa** [comment]
> wouldn't it be desirable to also render the descender and a line gap under the font, when creating the SVG?

In the context of making OT-SVG fonts it's not desirable because the viewBox plays a role in how the SVG artwork is scaled and positioned within the line of text. If you start changing the viewBox to, for example, vertically center the paths within the window, all of the SVGs will also be vertically centered which is definitely not desired.

**Comment by davidgodzsak** [comment]
I created a PR for this https://github.com/adobe-type-tools/opentype-svg/pull/23, behind a flag.

**Comment by miguelsousa** [comment]
Fixed by #23
