### ISSUE TITLE
it is not a valid folder path

### ISSUE THREAD

**Issue by RePlayer2** [adobe-type-tools/opentype-svg#29]
I use the OTF (Zebrawood. otf) file from the font file and the SVG file from the test file to run the code in the Command Line Window, which shows that it is not a valid folder path
![微信截图_20240511215750](https://github.com/adobe-type-tools/opentype-svg/assets/142655210/b953c603-ae7c-47ad-a700-d7d786d13486)

**Comment by miguelsousa** [comment]
`svg_folder_path` and `input_path` are positional arguments, not optional arguments, therefore the paths should not be preceded by any arguments. Try the following command instead:

    python addsvg.py "H:\test_py\opentypesvg\" "H:\test_py\opentypesvg\Zebrawood.otf"

**Comment by RePlayer2** [comment]
Thank you for answering my question，but i used your method the Command line Window still show”is not valid folder path“, 
I think ，I may need other ways to use the "addsvg.py" file
![image](https://github.com/adobe-type-tools/opentype-svg/assets/142655210/f93299df-f356-4952-9276-bdfb63560bd3)

**Comment by miguelsousa** [comment]
@RePlayer2 what output do you get when you run this command:

    addsvg --help

Don't add anything to the command above. If `opentypesvg` was installed via `pip` you should be able to run the command above from any directory.

**Comment by RePlayer2** [comment]
@miguelsousa 
This is my command used "addsvg --help“
![image](https://github.com/adobe-type-tools/opentype-svg/assets/142655210/6536c643-d80f-4e71-ab0e-b98c56cb7d1e)
the English means is roughly ‘addsvg’ is not an internal or external command, nor is it a runnable  program or bathc file
however, I sure "pip instal opentypesvg"and "pip install -u pip"
this is result
![image](https://github.com/adobe-type-tools/opentype-svg/assets/142655210/bed634fd-e8a5-4661-87be-0ed3fcd13370)

but my PyCharm is run this issue‘s code ,in the picture below
![image](https://github.com/adobe-type-tools/opentype-svg/assets/142655210/bfbade3f-d92d-45b4-8407-8cfce72346fe)
add to used library of opentypesvg succeed run my code，my pythons  version is 3.8 ，ued venv all contain opentype-svg
but is not use "addsvg --help" or "run code addsvg in pycharm"，Whether it's "pip install opentype svg" or "addsvg code"
the troubel is feel at a loss for me
![image](https://github.com/adobe-type-tools/opentype-svg/assets/142655210/0fd6b8a2-4724-4fbb-b62f-1ccf5a698a44)

![image](https://github.com/adobe-type-tools/opentype-svg/assets/142655210/2a4031e4-e819-4a80-986a-b389f293a0ce)

**Comment by miguelsousa** [comment]
OK, let's go step by step:

1. Create a virtual environment 
    ```sh
    python -m venv ot-svg
    ```
2. Activate the virtual environment
    ```sh
    ot-svg\Scripts\activate.bat
    ```
3. Install `opentypesvg` package
    ```sh
    python -m pip install opentypesvg
    ```
4. Get the help for `addsvg` tool
    ```sh
    addsvg --help
    ```

**Comment by RePlayer2** [comment]
It looks like it worked
![image](https://github.com/adobe-type-tools/opentype-svg/assets/142655210/c9e8ed72-714e-4d7b-b5f0-3026010c716d)

![image](https://github.com/adobe-type-tools/opentype-svg/assets/142655210/a79194de-6e87-469c-af2b-3e9a2779eeb3)
it's greate ,Thank you for your Patient help，
![image](https://github.com/adobe-type-tools/opentype-svg/assets/142655210/2587b699-93f6-456e-9e12-7e6fd5e6b532)
i can used addsvg to generate fonts show in word
