### ISSUE TITLE
support cid-keyed OTF

### ISSUE THREAD

**Issue by hatchzo** [adobe-type-tools/opentype-svg#4]
The "addSVGtable.py" doesn't seem to support cid-keyed OTF. 

Actually, the script adds SVG table into the font exactly and GID value are specified to bind SVG data with their parent B/W glyphs. 

CID-keyed CFF is used to Japanese or CK OTF development in common, and CID will correspond with GID entirely in most cases. 

However in some particular cases, for example, a subset font that is developed as a portion of Adobe CJK glyph collection, it will not have CID=GID mapping.

The key/val <endGlyphID="[GID]" startGlyphID="[GID]"> in SVG table seems to be specified as a toggle to show up a color glyph, it will make a conflict if cid-keyed font have an inconsistent CID/GID mapping.

**Comment by kenlunde** [comment]
The best way to describe this request is for the `addSVGtable.py` script to support CID-keyed fonts whose CIDs do not equal GIDs, particularly when the SVG glyphs correspond to CIDs that do not equal GIDs.

**Comment by miguelsousa** [comment]
@kenlunde got it. What the correct way to identify such difference? The fonts will have a specific ROSS?

**Comment by kenlunde** [comment]
Yes, the presence of /Registry, /Ordering, and /Supplement (aka ROS) values in the 'CFF ' table is the best indicator that you're dealing with a CID-keyed font.

**Comment by miguelsousa** [comment]
@kenlunde my question was, how do I distinguish between a CID-keyed font whose CID=GID from a CID-keyed font whose CID!=GID ?

**Comment by kenlunde** [comment]
Use `tx -4 <CID-keyed font>` for this. The moment that "tag" (aka GID) does not equal "cid" (aka CID), you're dealing with such a font.

**Comment by miguelsousa** [comment]
@kenlunde I don't want to call `tx` from `addSVGtable.py`. Any other suggestions?

**Comment by kenlunde** [comment]
The only place where CIDs are recorded in an OpenType/CFF font is the 'CFF ' table, so if you cannot call `tx` to check this, perhaps the best course of action is to simply assume that CID!=GID, meaning that all CID-keyed fonts are treated the same regardless of whether CID=GID or CID!=GID.

**Comment by miguelsousa** [comment]
I know I need to check the CFF table. I plan to do that using fonttools, since addSVGtable already depends on it. My questions were for trying to understand which parts of the CFF table I need to pay close attention to. Anyways, I'll figure it out.

**Comment by miguelsousa** [comment]
@hatchzo I made some tests with fonts I got from @kenlunde and as far as I can tell `addSVGtable.py` is working correctly with CJK fonts, even with those whose CIDs are different from GIDs.

Here's a test I ran using [SourceHanSansJP-Heavy.otf](https://github.com/adobe-fonts/source-han-sans/blob/release/SubsetOTF/JP/SourceHanSansJP-Heavy.otf):
```sh
python fonts2svg.py -c ff0000 -g cid00364,cid00621 SourceHanSansJP-Heavy.otf
python addSVGtable.py -s SVGs SourceHanSansJP-Heavy.otf
```
As you can see from the image below, the SVG artwork got associated with the expected glyphs.
<img width="1004" alt="screen shot 2018-02-16 at 17 47 09" src="https://user-images.githubusercontent.com/2119742/36336913-87e20f52-1341-11e8-8825-f1aee8bdc22f.png">

So the only issue I see is the inconvenience of having to zero-pad the CID references. I can change the scripts in this repository to handle unpadded CID reference. Would this be helpful to you?

**Comment by hatchzo** [comment]
OK, I will test new addSVGtable.py this week. Thanks!!
